services:
  db:
      image: postgres
      environment:
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      ports:
        - "15432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -p 5432"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - djangonetwork
  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@test.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
      ports:
        - "16543:80"
      depends_on:
        db:
          condition: service_healthy
      networks:
        - djangonetwork
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - djangonetwork
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
networks: 
  djangonetwork:
    driver: bridge