services:
  db:
      image: postgres:14-alpine
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - "15432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -p 5432"]
        interval: 5s
        timeout: 5s
        retries: 5
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
volumes:
  db-data: