services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - COMPOSEDEBUG=true
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8000:8000
      - 5678:5678