---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Environment Variables
        run: |
          echo "DB_USER=postgres" >> .env
          echo "DB_NAME=postgres" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=test@test.com" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=test" >> .env
          echo "DB_PASSWORD=postgres" >> .env
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
            docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: |
            docker-compose run --rm app sh -c "flake8"
      - name: Delete .env
        run: |
          rm .env